// <auto-generated />
using System;
using HeThongThuyetMinhDuLich.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HeThongThuyetMinhDuLich.Api.Migrations
{
    [DbContext(typeof(DuLichDbContext))]
    partial class DuLichDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HeThongThuyetMinhDuLich.Api.Models.DiemThamQuan", b =>
                {
                    b.Property<int>("MaDiem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDiem"));

                    b.Property<decimal>("BanKinhKichHoat")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("KinhDo")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<string>("MaDinhDanh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MaLoai")
                        .HasColumnType("int");

                    b.Property<int?>("MaTaiKhoanCapNhat")
                        .HasColumnType("int");

                    b.Property<int?>("MaTaiKhoanTao")
                        .HasColumnType("int");

                    b.Property<string>("MoTaNgan")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenDiem")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("TrangThaiHoatDong")
                        .HasColumnType("bit");

                    b.Property<decimal>("ViDo")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.HasKey("MaDiem");

                    b.HasIndex("MaDinhDanh")
                        .IsUnique();

                    b.HasIndex("MaLoai");

                    b.HasIndex("MaTaiKhoanCapNhat");

                    b.HasIndex("MaTaiKhoanTao");

                    b.HasIndex("ViDo", "KinhDo");

                    b.ToTable("DiemThamQuan", (string)null);
                });

            modelBuilder.Entity("HeThongThuyetMinhDuLich.Api.Models.HinhAnhDiemThamQuan", b =>
                {
                    b.Property<int>("MaHinhAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHinhAnh"));

                    b.Property<string>("DuongDanHinhAnh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("LaAnhDaiDien")
                        .HasColumnType("bit");

                    b.Property<int>("MaDiem")
                        .HasColumnType("int");

                    b.Property<int?>("MaTaiKhoanTao")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTaiLen")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenTepTin")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ThuTuHienThi")
                        .HasColumnType("int");

                    b.HasKey("MaHinhAnh");

                    b.HasIndex("MaDiem");

                    b.HasIndex("MaTaiKhoanTao");

                    b.ToTable("HinhAnhDiemThamQuan", (string)null);
                });

            modelBuilder.Entity("HeThongThuyetMinhDuLich.Api.Models.LichSuPhat", b =>
                {
                    b.Property<long>("MaLichSuPhat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MaLichSuPhat"));

                    b.Property<string>("CachKichHoat")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("MaDiem")
                        .HasColumnType("int");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int>("MaNoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ThoiLuongDaNghe")
                        .HasColumnType("int");

                    b.HasKey("MaLichSuPhat");

                    b.HasIndex("MaDiem");

                    b.HasIndex("MaNguoiDung");

                    b.HasIndex("MaNoiDung");

                    b.HasIndex("ThoiGianBatDau");

                    b.ToTable("LichSuPhat", null, t =>
                        {
                            t.HasCheckConstraint("CK_LichSuPhat_CachKichHoat", "[CachKichHoat] IN ('gps', 'qr', 'manual')");

                            t.HasCheckConstraint("CK_LichSuPhat_ThoiLuongDaNghe", "[ThoiLuongDaNghe] IS NULL OR [ThoiLuongDaNghe] >= 0");
                        });
                });

            modelBuilder.Entity("HeThongThuyetMinhDuLich.Api.Models.LoaiDiemThamQuan", b =>
                {
                    b.Property<int>("MaLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoai"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThaiHoatDong")
                        .HasColumnType("bit");

                    b.HasKey("MaLoai");

                    b.HasIndex("TenLoai")
                        .IsUnique();

                    b.ToTable("LoaiDiemThamQuan", (string)null);
                });

            modelBuilder.Entity("HeThongThuyetMinhDuLich.Api.Models.MaQr", b =>
                {
                    b.Property<int>("MaQR")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaQR"));

                    b.Property<string>("GiaTriQR")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaDiem")
                        .HasColumnType("int");

                    b.Property<int?>("MaTaiKhoanTao")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<bool>("TrangThaiHoatDong")
                        .HasColumnType("bit");

                    b.HasKey("MaQR");

                    b.HasIndex("GiaTriQR")
                        .IsUnique();

                    b.HasIndex("MaDiem");

                    b.HasIndex("MaTaiKhoanTao");

                    b.ToTable("MaQR", (string)null);
                });

            modelBuilder.Entity("HeThongThuyetMinhDuLich.Api.Models.NgonNgu", b =>
                {
                    b.Property<int>("MaNgonNgu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNgonNgu"));

                    b.Property<bool>("LaMacDinh")
                        .HasColumnType("bit");

                    b.Property<string>("MaNgonNguQuocTe")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TenNgonNgu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThaiHoatDong")
                        .HasColumnType("bit");

                    b.HasKey("MaNgonNgu");

                    b.HasIndex("MaNgonNguQuocTe")
                        .IsUnique();

                    b.ToTable("NgonNgu", (string)null);
                });

            modelBuilder.Entity("HeThongThuyetMinhDuLich.Api.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaNgonNguMacDinh")
                        .HasColumnType("int");

                    b.Property<string>("MatKhauMaHoa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenDangNhap")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThaiHoatDong")
                        .HasColumnType("bit");

                    b.HasKey("MaNguoiDung");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("MaNgonNguMacDinh");

                    b.HasIndex("TenDangNhap")
                        .IsUnique()
                        .HasFilter("[TenDangNhap] IS NOT NULL");

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("HeThongThuyetMinhDuLich.Api.Models.NoiDungThuyetMinh", b =>
                {
                    b.Property<int>("MaNoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNoiDung"));

                    b.Property<bool>("ChoPhepTTS")
                        .HasColumnType("bit");

                    b.Property<string>("DuongDanAmThanh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaDiem")
                        .HasColumnType("int");

                    b.Property<int>("MaNgonNgu")
                        .HasColumnType("int");

                    b.Property<int?>("MaTaiKhoanCapNhat")
                        .HasColumnType("int");

                    b.Property<int?>("MaTaiKhoanTao")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDungVanBan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ThoiLuongGiay")
                        .HasColumnType("int");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("TrangThaiHoatDong")
                        .HasColumnType("bit");

                    b.HasKey("MaNoiDung");

                    b.HasIndex("MaDiem");

                    b.HasIndex("MaNgonNgu");

                    b.HasIndex("MaTaiKhoanCapNhat");

                    b.HasIndex("MaTaiKhoanTao");

                    b.HasIndex("MaDiem", "MaNgonNgu")
                        .IsUnique();

                    b.ToTable("NoiDungThuyetMinh", (string)null);
                });

            modelBuilder.Entity("HeThongThuyetMinhDuLich.Api.Models.TaiKhoan", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTaiKhoan"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhauMaHoa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThaiHoatDong")
                        .HasColumnType("bit");

                    b.Property<string>("VaiTro")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaTaiKhoan");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("TaiKhoan", (string)null);
                });

            modelBuilder.Entity("HeThongThuyetMinhDuLich.Api.Models.DiemThamQuan", b =>
                {
                    b.HasOne("HeThongThuyetMinhDuLich.Api.Models.LoaiDiemThamQuan", "LoaiDiemThamQuan")
                        .WithMany("DiemThamQuans")
                        .HasForeignKey("MaLoai")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HeThongThuyetMinhDuLich.Api.Models.TaiKhoan", "TaiKhoanCapNhat")
                        .WithMany("DiemThamQuanDaCapNhats")
                        .HasForeignKey("MaTaiKhoanCapNhat")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("HeThongThuyetMinhDuLich.Api.Models.TaiKhoan", "TaiKhoanTao")
                        .WithMany("DiemThamQuanDaTaos")
                        .HasForeignKey("MaTaiKhoanTao")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("LoaiDiemThamQuan");

                    b.Navigation("TaiKhoanCapNhat");

                    b.Navigation("TaiKhoanTao");
                });

            modelBuilder.Entity("HeThongThuyetMinhDuLich.Api.Models.HinhAnhDiemThamQuan", b =>
                {
                    b.HasOne("HeThongThuyetMinhDuLich.Api.Models.DiemThamQuan", "DiemThamQuan")
                        .WithMany("HinhAnhDiemThamQuans")
                        .HasForeignKey("MaDiem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeThongThuyetMinhDuLich.Api.Models.TaiKhoan", "TaiKhoanTao")
                        .WithMany("HinhAnhDaTaos")
                        .HasForeignKey("MaTaiKhoanTao")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("DiemThamQuan");

                    b.Navigation("TaiKhoanTao");
                });

            modelBuilder.Entity("HeThongThuyetMinhDuLich.Api.Models.LichSuPhat", b =>
                {
                    b.HasOne("HeThongThuyetMinhDuLich.Api.Models.DiemThamQuan", "DiemThamQuan")
                        .WithMany("LichSuPhats")
                        .HasForeignKey("MaDiem")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HeThongThuyetMinhDuLich.Api.Models.NguoiDung", "NguoiDung")
                        .WithMany("LichSuPhats")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HeThongThuyetMinhDuLich.Api.Models.NoiDungThuyetMinh", "NoiDungThuyetMinh")
                        .WithMany("LichSuPhats")
                        .HasForeignKey("MaNoiDung")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DiemThamQuan");

                    b.Navigation("NguoiDung");

                    b.Navigation("NoiDungThuyetMinh");
                });

            modelBuilder.Entity("HeThongThuyetMinhDuLich.Api.Models.MaQr", b =>
                {
                    b.HasOne("HeThongThuyetMinhDuLich.Api.Models.DiemThamQuan", "DiemThamQuan")
                        .WithMany("MaQrs")
                        .HasForeignKey("MaDiem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeThongThuyetMinhDuLich.Api.Models.TaiKhoan", "TaiKhoanTao")
                        .WithMany("MaQrDaTaos")
                        .HasForeignKey("MaTaiKhoanTao")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("DiemThamQuan");

                    b.Navigation("TaiKhoanTao");
                });

            modelBuilder.Entity("HeThongThuyetMinhDuLich.Api.Models.NguoiDung", b =>
                {
                    b.HasOne("HeThongThuyetMinhDuLich.Api.Models.NgonNgu", "NgonNguMacDinh")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("MaNgonNguMacDinh");

                    b.Navigation("NgonNguMacDinh");
                });

            modelBuilder.Entity("HeThongThuyetMinhDuLich.Api.Models.NoiDungThuyetMinh", b =>
                {
                    b.HasOne("HeThongThuyetMinhDuLich.Api.Models.DiemThamQuan", "DiemThamQuan")
                        .WithMany("NoiDungThuyetMinhs")
                        .HasForeignKey("MaDiem")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HeThongThuyetMinhDuLich.Api.Models.NgonNgu", "NgonNgu")
                        .WithMany("NoiDungThuyetMinhs")
                        .HasForeignKey("MaNgonNgu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HeThongThuyetMinhDuLich.Api.Models.TaiKhoan", "TaiKhoanCapNhat")
                        .WithMany("NoiDungDaCapNhats")
                        .HasForeignKey("MaTaiKhoanCapNhat")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("HeThongThuyetMinhDuLich.Api.Models.TaiKhoan", "TaiKhoanTao")
                        .WithMany("NoiDungDaTaos")
                        .HasForeignKey("MaTaiKhoanTao")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("DiemThamQuan");

                    b.Navigation("NgonNgu");

                    b.Navigation("TaiKhoanCapNhat");

                    b.Navigation("TaiKhoanTao");
                });

            modelBuilder.Entity("HeThongThuyetMinhDuLich.Api.Models.DiemThamQuan", b =>
                {
                    b.Navigation("HinhAnhDiemThamQuans");

                    b.Navigation("LichSuPhats");

                    b.Navigation("MaQrs");

                    b.Navigation("NoiDungThuyetMinhs");
                });

            modelBuilder.Entity("HeThongThuyetMinhDuLich.Api.Models.LoaiDiemThamQuan", b =>
                {
                    b.Navigation("DiemThamQuans");
                });

            modelBuilder.Entity("HeThongThuyetMinhDuLich.Api.Models.NgonNgu", b =>
                {
                    b.Navigation("NguoiDungs");

                    b.Navigation("NoiDungThuyetMinhs");
                });

            modelBuilder.Entity("HeThongThuyetMinhDuLich.Api.Models.NguoiDung", b =>
                {
                    b.Navigation("LichSuPhats");
                });

            modelBuilder.Entity("HeThongThuyetMinhDuLich.Api.Models.NoiDungThuyetMinh", b =>
                {
                    b.Navigation("LichSuPhats");
                });

            modelBuilder.Entity("HeThongThuyetMinhDuLich.Api.Models.TaiKhoan", b =>
                {
                    b.Navigation("DiemThamQuanDaCapNhats");

                    b.Navigation("DiemThamQuanDaTaos");

                    b.Navigation("HinhAnhDaTaos");

                    b.Navigation("MaQrDaTaos");

                    b.Navigation("NoiDungDaCapNhats");

                    b.Navigation("NoiDungDaTaos");
                });
#pragma warning restore 612, 618
        }
    }
}
